/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 89
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 83
#define ALIAS_COUNT 0
#define TOKEN_COUNT 53
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym__s_n = 2,
  anon_sym_SLASH_STAR_BANG = 3,
  anon_sym_STAR_SLASH = 4,
  aux_sym_head_chunk_token1 = 5,
  anon_sym_COLON = 6,
  aux_sym_head_chunk_token2 = 7,
  anon_sym_EQ = 8,
  anon_sym_GT = 9,
  anon_sym_LT = 10,
  anon_sym_SLASH = 11,
  aux_sym_head_chunk_token3 = 12,
  sym_s_rr = 13,
  sym_s_2r = 14,
  aux_sym_text_line_token1 = 15,
  aux_sym_text_line_token2 = 16,
  sym_s_def = 17,
  sym_list_t = 18,
  sym_s_list_sep = 19,
  anon_sym_PIPE = 20,
  anon_sym_CR = 21,
  sym_s_lr = 22,
  aux_sym__comment_token1 = 23,
  anon_sym_STAR = 24,
  anon_sym_SLASH_STAR = 25,
  anon_sym_LBRACE = 26,
  anon_sym_RBRACE = 27,
  anon_sym_COMMA = 28,
  anon_sym_LBRACK = 29,
  anon_sym_RBRACK = 30,
  anon_sym_null = 31,
  anon_sym_Null = 32,
  anon_sym_NULL = 33,
  anon_sym_BANG_BANGnull = 34,
  aux_sym_null_scalar_token1 = 35,
  anon_sym_SQUOTE_SQUOTE = 36,
  anon_sym_true = 37,
  anon_sym_True = 38,
  anon_sym_TRUE = 39,
  anon_sym_false = 40,
  anon_sym_False = 41,
  anon_sym_FALSE = 42,
  sym_integer_scalar = 43,
  sym_float_scalar = 44,
  anon_sym_DQUOTE = 45,
  anon_sym_SQUOTE = 46,
  aux_sym__double_quoted_string_content_token1 = 47,
  sym__single_quoted_string_content = 48,
  sym_escape_sequence = 49,
  aux_sym_plain_scalar_token1 = 50,
  aux_sym_plain_scalar_token2 = 51,
  aux_sym_plain_scalar_token3 = 52,
  sym_source_file = 53,
  sym_script_line = 54,
  sym_head_chunk = 55,
  sym_value_line = 56,
  sym_text_line = 57,
  sym_list_items = 58,
  sym_list_line = 59,
  sym_kvs_line = 60,
  sym_other_line = 61,
  sym__comment = 62,
  sym_comment = 63,
  sym_flow_node = 64,
  sym_flow_mapping = 65,
  sym_flow_mapping_entries = 66,
  sym_flow_mapping_entry = 67,
  sym_flow_sequence = 68,
  sym_flow_sequence_entries = 69,
  sym_scalar = 70,
  sym_null_scalar = 71,
  sym_boolean_scalar = 72,
  sym_quoted_scalar = 73,
  aux_sym__double_quoted_string_content = 74,
  sym_plain_scalar = 75,
  aux_sym_source_file_repeat1 = 76,
  aux_sym_head_chunk_repeat1 = 77,
  aux_sym_text_line_repeat1 = 78,
  aux_sym_list_items_repeat1 = 79,
  aux_sym_flow_mapping_entries_repeat1 = 80,
  aux_sym_flow_sequence_entries_repeat1 = 81,
  aux_sym_plain_scalar_repeat1 = 82,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym__s_n] = "_s_n",
  [anon_sym_SLASH_STAR_BANG] = "/*!",
  [anon_sym_STAR_SLASH] = "*/",
  [aux_sym_head_chunk_token1] = "head_chunk_token1",
  [anon_sym_COLON] = ":",
  [aux_sym_head_chunk_token2] = "head_chunk_token2",
  [anon_sym_EQ] = "=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH] = "/",
  [aux_sym_head_chunk_token3] = "head_chunk_token3",
  [sym_s_rr] = "s_rr",
  [sym_s_2r] = "s_2r",
  [aux_sym_text_line_token1] = "text_line_token1",
  [aux_sym_text_line_token2] = "text_line_token2",
  [sym_s_def] = "s_def",
  [sym_list_t] = "list_t",
  [sym_s_list_sep] = "s_list_sep",
  [anon_sym_PIPE] = "|",
  [anon_sym_CR] = "\r",
  [sym_s_lr] = "s_lr",
  [aux_sym__comment_token1] = "_comment_token1",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH_STAR] = "/*",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_null] = "null",
  [anon_sym_Null] = "Null",
  [anon_sym_NULL] = "NULL",
  [anon_sym_BANG_BANGnull] = "!!null",
  [aux_sym_null_scalar_token1] = "null_scalar_token1",
  [anon_sym_SQUOTE_SQUOTE] = "''",
  [anon_sym_true] = "true",
  [anon_sym_True] = "True",
  [anon_sym_TRUE] = "TRUE",
  [anon_sym_false] = "false",
  [anon_sym_False] = "False",
  [anon_sym_FALSE] = "FALSE",
  [sym_integer_scalar] = "integer_scalar",
  [sym_float_scalar] = "float_scalar",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__double_quoted_string_content_token1] = "_double_quoted_string_content_token1",
  [sym__single_quoted_string_content] = "_single_quoted_string_content",
  [sym_escape_sequence] = "escape_sequence",
  [aux_sym_plain_scalar_token1] = "plain_scalar_token1",
  [aux_sym_plain_scalar_token2] = "plain_scalar_token2",
  [aux_sym_plain_scalar_token3] = "plain_scalar_token3",
  [sym_source_file] = "source_file",
  [sym_script_line] = "script_line",
  [sym_head_chunk] = "head_chunk",
  [sym_value_line] = "value_line",
  [sym_text_line] = "text_line",
  [sym_list_items] = "list_items",
  [sym_list_line] = "list_line",
  [sym_kvs_line] = "kvs_line",
  [sym_other_line] = "other_line",
  [sym__comment] = "_comment",
  [sym_comment] = "comment",
  [sym_flow_node] = "flow_node",
  [sym_flow_mapping] = "flow_mapping",
  [sym_flow_mapping_entries] = "flow_mapping_entries",
  [sym_flow_mapping_entry] = "flow_mapping_entry",
  [sym_flow_sequence] = "flow_sequence",
  [sym_flow_sequence_entries] = "flow_sequence_entries",
  [sym_scalar] = "scalar",
  [sym_null_scalar] = "null_scalar",
  [sym_boolean_scalar] = "boolean_scalar",
  [sym_quoted_scalar] = "quoted_scalar",
  [aux_sym__double_quoted_string_content] = "_double_quoted_string_content",
  [sym_plain_scalar] = "plain_scalar",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_head_chunk_repeat1] = "head_chunk_repeat1",
  [aux_sym_text_line_repeat1] = "text_line_repeat1",
  [aux_sym_list_items_repeat1] = "list_items_repeat1",
  [aux_sym_flow_mapping_entries_repeat1] = "flow_mapping_entries_repeat1",
  [aux_sym_flow_sequence_entries_repeat1] = "flow_sequence_entries_repeat1",
  [aux_sym_plain_scalar_repeat1] = "plain_scalar_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym__s_n] = sym__s_n,
  [anon_sym_SLASH_STAR_BANG] = anon_sym_SLASH_STAR_BANG,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [aux_sym_head_chunk_token1] = aux_sym_head_chunk_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_head_chunk_token2] = aux_sym_head_chunk_token2,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [aux_sym_head_chunk_token3] = aux_sym_head_chunk_token3,
  [sym_s_rr] = sym_s_rr,
  [sym_s_2r] = sym_s_2r,
  [aux_sym_text_line_token1] = aux_sym_text_line_token1,
  [aux_sym_text_line_token2] = aux_sym_text_line_token2,
  [sym_s_def] = sym_s_def,
  [sym_list_t] = sym_list_t,
  [sym_s_list_sep] = sym_s_list_sep,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_CR] = anon_sym_CR,
  [sym_s_lr] = sym_s_lr,
  [aux_sym__comment_token1] = aux_sym__comment_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_Null] = anon_sym_Null,
  [anon_sym_NULL] = anon_sym_NULL,
  [anon_sym_BANG_BANGnull] = anon_sym_BANG_BANGnull,
  [aux_sym_null_scalar_token1] = aux_sym_null_scalar_token1,
  [anon_sym_SQUOTE_SQUOTE] = anon_sym_SQUOTE_SQUOTE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_True] = anon_sym_True,
  [anon_sym_TRUE] = anon_sym_TRUE,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_False] = anon_sym_False,
  [anon_sym_FALSE] = anon_sym_FALSE,
  [sym_integer_scalar] = sym_integer_scalar,
  [sym_float_scalar] = sym_float_scalar,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__double_quoted_string_content_token1] = aux_sym__double_quoted_string_content_token1,
  [sym__single_quoted_string_content] = sym__single_quoted_string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [aux_sym_plain_scalar_token1] = aux_sym_plain_scalar_token1,
  [aux_sym_plain_scalar_token2] = aux_sym_plain_scalar_token2,
  [aux_sym_plain_scalar_token3] = aux_sym_plain_scalar_token3,
  [sym_source_file] = sym_source_file,
  [sym_script_line] = sym_script_line,
  [sym_head_chunk] = sym_head_chunk,
  [sym_value_line] = sym_value_line,
  [sym_text_line] = sym_text_line,
  [sym_list_items] = sym_list_items,
  [sym_list_line] = sym_list_line,
  [sym_kvs_line] = sym_kvs_line,
  [sym_other_line] = sym_other_line,
  [sym__comment] = sym__comment,
  [sym_comment] = sym_comment,
  [sym_flow_node] = sym_flow_node,
  [sym_flow_mapping] = sym_flow_mapping,
  [sym_flow_mapping_entries] = sym_flow_mapping_entries,
  [sym_flow_mapping_entry] = sym_flow_mapping_entry,
  [sym_flow_sequence] = sym_flow_sequence,
  [sym_flow_sequence_entries] = sym_flow_sequence_entries,
  [sym_scalar] = sym_scalar,
  [sym_null_scalar] = sym_null_scalar,
  [sym_boolean_scalar] = sym_boolean_scalar,
  [sym_quoted_scalar] = sym_quoted_scalar,
  [aux_sym__double_quoted_string_content] = aux_sym__double_quoted_string_content,
  [sym_plain_scalar] = sym_plain_scalar,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_head_chunk_repeat1] = aux_sym_head_chunk_repeat1,
  [aux_sym_text_line_repeat1] = aux_sym_text_line_repeat1,
  [aux_sym_list_items_repeat1] = aux_sym_list_items_repeat1,
  [aux_sym_flow_mapping_entries_repeat1] = aux_sym_flow_mapping_entries_repeat1,
  [aux_sym_flow_sequence_entries_repeat1] = aux_sym_flow_sequence_entries_repeat1,
  [aux_sym_plain_scalar_repeat1] = aux_sym_plain_scalar_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__s_n] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH_STAR_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_head_chunk_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_head_chunk_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_head_chunk_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_s_rr] = {
    .visible = true,
    .named = true,
  },
  [sym_s_2r] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_line_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_s_def] = {
    .visible = true,
    .named = true,
  },
  [sym_list_t] = {
    .visible = true,
    .named = true,
  },
  [sym_s_list_sep] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [sym_s_lr] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NULL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_BANGnull] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_null_scalar_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_True] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TRUE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_False] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FALSE] = {
    .visible = true,
    .named = false,
  },
  [sym_integer_scalar] = {
    .visible = true,
    .named = true,
  },
  [sym_float_scalar] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__double_quoted_string_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__single_quoted_string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_plain_scalar_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_plain_scalar_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_plain_scalar_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_script_line] = {
    .visible = true,
    .named = true,
  },
  [sym_head_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_value_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_list_items] = {
    .visible = true,
    .named = true,
  },
  [sym_list_line] = {
    .visible = true,
    .named = true,
  },
  [sym_kvs_line] = {
    .visible = true,
    .named = true,
  },
  [sym_other_line] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_node] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_mapping] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_mapping_entries] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_mapping_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_sequence_entries] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar] = {
    .visible = true,
    .named = true,
  },
  [sym_null_scalar] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_scalar] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_scalar] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__double_quoted_string_content] = {
    .visible = false,
    .named = false,
  },
  [sym_plain_scalar] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_head_chunk_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_items_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_flow_mapping_entries_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_flow_sequence_entries_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_plain_scalar_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_cmd = 1,
  field_key = 2,
  field_s = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_cmd] = "cmd",
  [field_key] = "key",
  [field_s] = "s",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 2},
  [8] = {.index = 8, .length = 2},
  [9] = {.index = 10, .length = 2},
  [10] = {.index = 12, .length = 1},
  [11] = {.index = 13, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_cmd, 1},
  [1] =
    {field_value, 2},
  [2] =
    {field_s, 0},
  [3] =
    {field_s, 0, .inherited = true},
  [4] =
    {field_key, 0},
  [5] =
    {field_value, 0},
  [6] =
    {field_s, 0, .inherited = true},
    {field_s, 1, .inherited = true},
  [8] =
    {field_value, 0},
    {field_value, 1, .inherited = true},
  [10] =
    {field_key, 0},
    {field_value, 2},
  [12] =
    {field_value, 1},
  [13] =
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
};

static const TSCharacterRange aux_sym_plain_scalar_token1_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '+'}, {'-', '9'}, {';', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(60);
      ADVANCE_MAP(
        '\n', 62,
        '\r', 93,
        '"', 128,
        '\'', 129,
        '*', 98,
        ',', 107,
        '/', 78,
        ':', 67,
        '<', 76,
        '=', 72,
        '>', 74,
        '[', 108,
        ']', 109,
        '{', 105,
        '|', 91,
        '}', 106,
        '\t', 71,
        ' ', 71,
        0x0b, 70,
        '\f', 70,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(62);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead == '\r') ADVANCE(93);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == '|') ADVANCE(92);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0) ADVANCE(89);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '\'', 10,
        '*', 99,
        ',', 107,
        '/', 11,
        ':', 67,
        '[', 108,
        ']', 109,
        'n', 45,
        '{', 105,
        '}', 106,
        '\t', 114,
        ' ', 114,
      );
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '*', 66,
        '/', 78,
        ':', 68,
        '<', 77,
        '=', 73,
        '>', 75,
        '\t', 65,
        ' ', 65,
      );
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        ',', 107,
        '/', 146,
        ':', 69,
        ']', 109,
        '}', 106,
        '\t', 114,
        ' ', 114,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(147);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '/', 78,
        ':', 68,
        '<', 77,
        '=', 73,
        '>', 75,
        '\t', 65,
        ' ', 65,
      );
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '/') ADVANCE(78);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '/', 11,
        ':', 16,
        '<', 17,
        '=', 18,
        '>', 19,
        '\t', 114,
        ' ', 114,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(128);
      if (lookahead == '/') ADVANCE(130);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(131);
      END_STATE();
    case 10:
      if (lookahead == '\'') ADVANCE(117);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(100);
      END_STATE();
    case 12:
      if (lookahead == '*') ADVANCE(99);
      if (lookahead == '/') ADVANCE(95);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(97);
      END_STATE();
    case 13:
      if (lookahead == '.') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '/') ADVANCE(132);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(133);
      END_STATE();
    case 15:
      if (lookahead == '/') ADVANCE(85);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '*') ADVANCE(84);
      END_STATE();
    case 16:
      if (lookahead == '=') ADVANCE(87);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(94);
      END_STATE();
    case 18:
      if (lookahead == '>') ADVANCE(81);
      END_STATE();
    case 19:
      if (lookahead == '>') ADVANCE(80);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(120);
      END_STATE();
    case 21:
      if (lookahead == 'E') ADVANCE(123);
      END_STATE();
    case 22:
      if (lookahead == 'L') ADVANCE(25);
      END_STATE();
    case 23:
      if (lookahead == 'L') ADVANCE(112);
      END_STATE();
    case 24:
      if (lookahead == 'L') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'S') ADVANCE(21);
      END_STATE();
    case 26:
      if (lookahead == 'U') ADVANCE(20);
      END_STATE();
    case 27:
      ADVANCE_MAP(
        'U', 57,
        'u', 53,
        ' ', 134,
        '"', 134,
        '/', 134,
        '0', 134,
        '\\', 134,
        'a', 134,
        'b', 134,
        'e', 134,
        'f', 134,
        'n', 134,
        'r', 134,
        't', 134,
        'v', 134,
      );
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(119);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(118);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(122);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(121);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(111);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(110);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(113);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 39:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 45:
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 46:
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 47:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(134);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(54);
      END_STATE();
    case 56:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(55);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(56);
      END_STATE();
    case 58:
      if (eof) ADVANCE(60);
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '!', 136,
        '"', 128,
        '\'', 129,
        ',', 107,
        '.', 145,
        '/', 137,
        '0', 124,
        ':', 67,
        'F', 139,
        'N', 141,
        'T', 140,
        '[', 108,
        ']', 109,
        'f', 142,
        'n', 144,
        't', 143,
        '{', 105,
        '}', 106,
        '\t', 114,
        ' ', 114,
        '+', 138,
        '-', 138,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(125);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(135);
      END_STATE();
    case 59:
      if (eof) ADVANCE(60);
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '/', 79,
        ':', 67,
        '<', 76,
        '=', 72,
        '>', 74,
        '\t', 65,
        ' ', 65,
      );
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__s_n);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR_BANG);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_head_chunk_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/' &&
          lookahead != ':' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_head_chunk_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/' &&
          lookahead != ':' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(87);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_COLON);
      if ((!eof && set_contains(aux_sym_plain_scalar_token1_character_set_1, 9, lookahead)) ||
          lookahead == ':') ADVANCE(148);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_head_chunk_token2);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_head_chunk_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(114);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(81);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(80);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '>') ADVANCE(94);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(100);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(101);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_s_rr);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_s_2r);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_text_line_token2);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_text_line_token2);
      if (lookahead == '*') ADVANCE(100);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_text_line_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(114);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_s_def);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_list_t);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/' &&
          lookahead != '|') ADVANCE(89);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_list_t);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/' &&
          lookahead != '|') ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_s_list_sep);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(90);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(62);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_s_lr);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym__comment_token1);
      if (lookahead == '*') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(97);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym__comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(97);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym__comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '/') ADVANCE(64);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '!') ADVANCE(63);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if ((!eof && set_contains(aux_sym_plain_scalar_token1_character_set_1, 9, lookahead))) ADVANCE(147);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(131);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(133);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_Null);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_NULL);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_BANG_BANGnull);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_null_scalar_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_null_scalar_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(131);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_null_scalar_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(133);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_SQUOTE_SQUOTE);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_True);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_TRUE);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_False);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_FALSE);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_integer_scalar);
      if (lookahead == '.') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_integer_scalar);
      if (lookahead == '.') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_float_scalar);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_float_scalar);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym__double_quoted_string_content_token1);
      if (lookahead == '*') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(131);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym__double_quoted_string_content_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(131);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym__single_quoted_string_content);
      if (lookahead == '*') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(133);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym__single_quoted_string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(133);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token1);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token1);
      if (lookahead == '!') ADVANCE(40);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token1);
      if (lookahead == '*') ADVANCE(100);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token1);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == '0') ADVANCE(124);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token1);
      if (lookahead == 'A') ADVANCE(22);
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token1);
      if (lookahead == 'R') ADVANCE(26);
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token1);
      if (lookahead == 'U') ADVANCE(24);
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token1);
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token1);
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token1);
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token2);
      if (lookahead == '*') ADVANCE(102);
      if ((!eof && set_contains(aux_sym_plain_scalar_token1_character_set_1, 9, lookahead))) ADVANCE(147);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token2);
      if ((!eof && set_contains(aux_sym_plain_scalar_token1_character_set_1, 9, lookahead))) ADVANCE(147);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(aux_sym_plain_scalar_token3);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 59},
  [2] = {.lex_state = 58},
  [3] = {.lex_state = 58},
  [4] = {.lex_state = 58},
  [5] = {.lex_state = 58},
  [6] = {.lex_state = 58},
  [7] = {.lex_state = 58},
  [8] = {.lex_state = 58},
  [9] = {.lex_state = 58},
  [10] = {.lex_state = 58},
  [11] = {.lex_state = 58},
  [12] = {.lex_state = 58},
  [13] = {.lex_state = 59},
  [14] = {.lex_state = 59},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 59},
  [22] = {.lex_state = 59},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 58},
  [37] = {.lex_state = 58},
  [38] = {.lex_state = 58},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 58},
  [42] = {.lex_state = 58},
  [43] = {.lex_state = 58},
  [44] = {.lex_state = 58},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 12},
  [47] = {.lex_state = 58},
  [48] = {.lex_state = 12},
  [49] = {.lex_state = 9},
  [50] = {.lex_state = 7},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 58},
  [53] = {.lex_state = 12},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 58},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 9},
  [60] = {.lex_state = 58},
  [61] = {.lex_state = 58},
  [62] = {.lex_state = 58},
  [63] = {.lex_state = 7},
  [64] = {.lex_state = 58},
  [65] = {.lex_state = 58},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 58},
  [69] = {.lex_state = 58},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 58},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 58},
  [74] = {.lex_state = 58},
  [75] = {.lex_state = 8},
  [76] = {.lex_state = 58},
  [77] = {.lex_state = 14},
  [78] = {.lex_state = 58},
  [79] = {.lex_state = 58},
  [80] = {.lex_state = 15},
  [81] = {.lex_state = 58},
  [82] = {.lex_state = 58},
  [83] = {.lex_state = 58},
  [84] = {.lex_state = 58},
  [85] = {.lex_state = 58},
  [86] = {(TSStateId)(-1),},
  [87] = {(TSStateId)(-1),},
  [88] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__s_n] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_head_chunk_token2] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [aux_sym_head_chunk_token3] = ACTIONS(1),
    [aux_sym_text_line_token2] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_CR] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_null_scalar_token1] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_plain_scalar_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(74),
    [sym_script_line] = STATE(84),
    [sym_head_chunk] = STATE(39),
    [sym_value_line] = STATE(84),
    [sym_text_line] = STATE(84),
    [sym_list_line] = STATE(84),
    [sym_kvs_line] = STATE(84),
    [sym_other_line] = STATE(84),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(14),
    [aux_sym_head_chunk_repeat1] = STATE(18),
    [sym__s_n] = ACTIONS(7),
    [anon_sym_SLASH_STAR_BANG] = ACTIONS(9),
    [aux_sym_head_chunk_token1] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_SLASH_STAR] = ACTIONS(17),
    [aux_sym_null_scalar_token1] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_BANG_BANGnull,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(33), 1,
      sym_integer_scalar,
    ACTIONS(35), 1,
      sym_float_scalar,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      aux_sym_plain_scalar_token1,
    STATE(2), 1,
      sym_comment,
    STATE(44), 1,
      sym_flow_node,
    STATE(61), 1,
      sym_flow_mapping_entry,
    ACTIONS(19), 2,
      sym__s_n,
      anon_sym_RBRACE,
    ACTIONS(25), 3,
      anon_sym_null,
      anon_sym_Null,
      anon_sym_NULL,
    STATE(43), 3,
      sym_flow_mapping,
      sym_flow_sequence,
      sym_scalar,
    STATE(41), 4,
      sym_null_scalar,
      sym_boolean_scalar,
      sym_quoted_scalar,
      sym_plain_scalar,
    ACTIONS(31), 6,
      anon_sym_true,
      anon_sym_True,
      anon_sym_TRUE,
      anon_sym_false,
      anon_sym_False,
      anon_sym_FALSE,
  [68] = 19,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_BANG_BANGnull,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(33), 1,
      sym_integer_scalar,
    ACTIONS(35), 1,
      sym_float_scalar,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      aux_sym_plain_scalar_token1,
    ACTIONS(43), 1,
      sym__s_n,
    STATE(3), 1,
      sym_comment,
    STATE(44), 1,
      sym_flow_node,
    STATE(47), 1,
      sym_flow_mapping_entry,
    STATE(78), 1,
      sym_flow_mapping_entries,
    ACTIONS(25), 3,
      anon_sym_null,
      anon_sym_Null,
      anon_sym_NULL,
    STATE(43), 3,
      sym_flow_mapping,
      sym_flow_sequence,
      sym_scalar,
    STATE(41), 4,
      sym_null_scalar,
      sym_boolean_scalar,
      sym_quoted_scalar,
      sym_plain_scalar,
    ACTIONS(31), 6,
      anon_sym_true,
      anon_sym_True,
      anon_sym_TRUE,
      anon_sym_false,
      anon_sym_False,
      anon_sym_FALSE,
  [138] = 19,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_BANG_BANGnull,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(33), 1,
      sym_integer_scalar,
    ACTIONS(35), 1,
      sym_float_scalar,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      aux_sym_plain_scalar_token1,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      sym_comment,
    STATE(44), 1,
      sym_flow_node,
    STATE(47), 1,
      sym_flow_mapping_entry,
    STATE(76), 1,
      sym_flow_mapping_entries,
    ACTIONS(25), 3,
      anon_sym_null,
      anon_sym_Null,
      anon_sym_NULL,
    STATE(43), 3,
      sym_flow_mapping,
      sym_flow_sequence,
      sym_scalar,
    STATE(41), 4,
      sym_null_scalar,
      sym_boolean_scalar,
      sym_quoted_scalar,
      sym_plain_scalar,
    ACTIONS(31), 6,
      anon_sym_true,
      anon_sym_True,
      anon_sym_TRUE,
      anon_sym_false,
      anon_sym_False,
      anon_sym_FALSE,
  [208] = 17,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_BANG_BANGnull,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(33), 1,
      sym_integer_scalar,
    ACTIONS(35), 1,
      sym_float_scalar,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      aux_sym_plain_scalar_token1,
    STATE(5), 1,
      sym_comment,
    STATE(62), 1,
      sym_flow_node,
    ACTIONS(25), 3,
      anon_sym_null,
      anon_sym_Null,
      anon_sym_NULL,
    ACTIONS(47), 3,
      sym__s_n,
      anon_sym_RBRACE,
      anon_sym_COMMA,
    STATE(43), 3,
      sym_flow_mapping,
      sym_flow_sequence,
      sym_scalar,
    STATE(41), 4,
      sym_null_scalar,
      sym_boolean_scalar,
      sym_quoted_scalar,
      sym_plain_scalar,
    ACTIONS(31), 6,
      anon_sym_true,
      anon_sym_True,
      anon_sym_TRUE,
      anon_sym_false,
      anon_sym_False,
      anon_sym_FALSE,
  [274] = 18,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_BANG_BANGnull,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(33), 1,
      sym_integer_scalar,
    ACTIONS(35), 1,
      sym_float_scalar,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      aux_sym_plain_scalar_token1,
    STATE(6), 1,
      sym_comment,
    STATE(44), 1,
      sym_flow_node,
    STATE(61), 1,
      sym_flow_mapping_entry,
    ACTIONS(49), 2,
      sym__s_n,
      anon_sym_RBRACE,
    ACTIONS(25), 3,
      anon_sym_null,
      anon_sym_Null,
      anon_sym_NULL,
    STATE(43), 3,
      sym_flow_mapping,
      sym_flow_sequence,
      sym_scalar,
    STATE(41), 4,
      sym_null_scalar,
      sym_boolean_scalar,
      sym_quoted_scalar,
      sym_plain_scalar,
    ACTIONS(31), 6,
      anon_sym_true,
      anon_sym_True,
      anon_sym_TRUE,
      anon_sym_false,
      anon_sym_False,
      anon_sym_FALSE,
  [342] = 18,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_BANG_BANGnull,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(33), 1,
      sym_integer_scalar,
    ACTIONS(35), 1,
      sym_float_scalar,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      aux_sym_plain_scalar_token1,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    STATE(7), 1,
      sym_comment,
    STATE(64), 1,
      sym_flow_node,
    STATE(82), 1,
      sym_flow_sequence_entries,
    ACTIONS(25), 3,
      anon_sym_null,
      anon_sym_Null,
      anon_sym_NULL,
    STATE(43), 3,
      sym_flow_mapping,
      sym_flow_sequence,
      sym_scalar,
    STATE(41), 4,
      sym_null_scalar,
      sym_boolean_scalar,
      sym_quoted_scalar,
      sym_plain_scalar,
    ACTIONS(31), 6,
      anon_sym_true,
      anon_sym_True,
      anon_sym_TRUE,
      anon_sym_false,
      anon_sym_False,
      anon_sym_FALSE,
  [409] = 17,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_BANG_BANGnull,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(33), 1,
      sym_integer_scalar,
    ACTIONS(35), 1,
      sym_float_scalar,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      aux_sym_plain_scalar_token1,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    STATE(8), 1,
      sym_comment,
    STATE(68), 1,
      sym_flow_node,
    ACTIONS(25), 3,
      anon_sym_null,
      anon_sym_Null,
      anon_sym_NULL,
    STATE(43), 3,
      sym_flow_mapping,
      sym_flow_sequence,
      sym_scalar,
    STATE(41), 4,
      sym_null_scalar,
      sym_boolean_scalar,
      sym_quoted_scalar,
      sym_plain_scalar,
    ACTIONS(31), 6,
      anon_sym_true,
      anon_sym_True,
      anon_sym_TRUE,
      anon_sym_false,
      anon_sym_False,
      anon_sym_FALSE,
  [473] = 17,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_BANG_BANGnull,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(33), 1,
      sym_integer_scalar,
    ACTIONS(35), 1,
      sym_float_scalar,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      aux_sym_plain_scalar_token1,
    ACTIONS(55), 1,
      sym__s_n,
    STATE(9), 1,
      sym_comment,
    STATE(81), 1,
      sym_flow_node,
    ACTIONS(25), 3,
      anon_sym_null,
      anon_sym_Null,
      anon_sym_NULL,
    STATE(43), 3,
      sym_flow_mapping,
      sym_flow_sequence,
      sym_scalar,
    STATE(41), 4,
      sym_null_scalar,
      sym_boolean_scalar,
      sym_quoted_scalar,
      sym_plain_scalar,
    ACTIONS(31), 6,
      anon_sym_true,
      anon_sym_True,
      anon_sym_TRUE,
      anon_sym_false,
      anon_sym_False,
      anon_sym_FALSE,
  [537] = 17,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_BANG_BANGnull,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(33), 1,
      sym_integer_scalar,
    ACTIONS(35), 1,
      sym_float_scalar,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      aux_sym_plain_scalar_token1,
    ACTIONS(57), 1,
      anon_sym_RBRACK,
    STATE(10), 1,
      sym_comment,
    STATE(68), 1,
      sym_flow_node,
    ACTIONS(25), 3,
      anon_sym_null,
      anon_sym_Null,
      anon_sym_NULL,
    STATE(43), 3,
      sym_flow_mapping,
      sym_flow_sequence,
      sym_scalar,
    STATE(41), 4,
      sym_null_scalar,
      sym_boolean_scalar,
      sym_quoted_scalar,
      sym_plain_scalar,
    ACTIONS(31), 6,
      anon_sym_true,
      anon_sym_True,
      anon_sym_TRUE,
      anon_sym_false,
      anon_sym_False,
      anon_sym_FALSE,
  [601] = 17,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_BANG_BANGnull,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(33), 1,
      sym_integer_scalar,
    ACTIONS(35), 1,
      sym_float_scalar,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      aux_sym_plain_scalar_token1,
    STATE(11), 1,
      sym_comment,
    STATE(44), 1,
      sym_flow_node,
    STATE(61), 1,
      sym_flow_mapping_entry,
    ACTIONS(25), 3,
      anon_sym_null,
      anon_sym_Null,
      anon_sym_NULL,
    STATE(43), 3,
      sym_flow_mapping,
      sym_flow_sequence,
      sym_scalar,
    STATE(41), 4,
      sym_null_scalar,
      sym_boolean_scalar,
      sym_quoted_scalar,
      sym_plain_scalar,
    ACTIONS(31), 6,
      anon_sym_true,
      anon_sym_True,
      anon_sym_TRUE,
      anon_sym_false,
      anon_sym_False,
      anon_sym_FALSE,
  [665] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_BANG_BANGnull,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(33), 1,
      sym_integer_scalar,
    ACTIONS(35), 1,
      sym_float_scalar,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_SQUOTE,
    ACTIONS(41), 1,
      aux_sym_plain_scalar_token1,
    STATE(12), 1,
      sym_comment,
    STATE(68), 1,
      sym_flow_node,
    ACTIONS(25), 3,
      anon_sym_null,
      anon_sym_Null,
      anon_sym_NULL,
    STATE(43), 3,
      sym_flow_mapping,
      sym_flow_sequence,
      sym_scalar,
    STATE(41), 4,
      sym_null_scalar,
      sym_boolean_scalar,
      sym_quoted_scalar,
      sym_plain_scalar,
    ACTIONS(31), 6,
      anon_sym_true,
      anon_sym_True,
      anon_sym_TRUE,
      anon_sym_false,
      anon_sym_False,
      anon_sym_FALSE,
  [726] = 12,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      sym__s_n,
    ACTIONS(64), 1,
      anon_sym_SLASH_STAR_BANG,
    ACTIONS(67), 1,
      aux_sym_head_chunk_token1,
    ACTIONS(73), 1,
      anon_sym_SLASH,
    STATE(18), 1,
      aux_sym_head_chunk_repeat1,
    STATE(39), 1,
      sym_head_chunk,
    STATE(13), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    ACTIONS(70), 4,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    STATE(84), 6,
      sym_script_line,
      sym_value_line,
      sym_text_line,
      sym_list_line,
      sym_kvs_line,
      sym_other_line,
  [772] = 13,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(7), 1,
      sym__s_n,
    ACTIONS(9), 1,
      anon_sym_SLASH_STAR_BANG,
    ACTIONS(11), 1,
      aux_sym_head_chunk_token1,
    ACTIONS(15), 1,
      anon_sym_SLASH,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      aux_sym_source_file_repeat1,
    STATE(14), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_head_chunk_repeat1,
    STATE(39), 1,
      sym_head_chunk,
    ACTIONS(13), 4,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    STATE(84), 6,
      sym_script_line,
      sym_value_line,
      sym_text_line,
      sym_list_line,
      sym_kvs_line,
      sym_other_line,
  [820] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(82), 1,
      aux_sym_head_chunk_token3,
    STATE(15), 1,
      sym_comment,
    ACTIONS(80), 5,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(78), 6,
      sym__s_n,
      aux_sym_head_chunk_token1,
      sym_s_rr,
      sym_s_2r,
      sym_s_def,
      sym_s_lr,
  [848] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(82), 1,
      aux_sym_head_chunk_token2,
    STATE(16), 1,
      sym_comment,
    ACTIONS(80), 5,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(78), 6,
      sym__s_n,
      aux_sym_head_chunk_token1,
      sym_s_rr,
      sym_s_2r,
      sym_s_def,
      sym_s_lr,
  [876] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(86), 1,
      aux_sym_head_chunk_token1,
    ACTIONS(92), 1,
      anon_sym_SLASH,
    STATE(17), 2,
      sym_comment,
      aux_sym_head_chunk_repeat1,
    ACTIONS(89), 4,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(84), 5,
      sym__s_n,
      sym_s_rr,
      sym_s_2r,
      sym_s_def,
      sym_s_lr,
  [906] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(11), 1,
      aux_sym_head_chunk_token1,
    ACTIONS(15), 1,
      anon_sym_SLASH,
    STATE(17), 1,
      aux_sym_head_chunk_repeat1,
    STATE(18), 1,
      sym_comment,
    ACTIONS(97), 4,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(95), 5,
      sym__s_n,
      sym_s_rr,
      sym_s_2r,
      sym_s_def,
      sym_s_lr,
  [938] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    STATE(19), 1,
      sym_comment,
    ACTIONS(80), 5,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(78), 6,
      sym__s_n,
      aux_sym_head_chunk_token1,
      sym_s_rr,
      sym_s_2r,
      sym_s_def,
      sym_s_lr,
  [963] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    STATE(20), 1,
      sym_comment,
    ACTIONS(99), 5,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_SLASH,
    ACTIONS(84), 6,
      sym__s_n,
      aux_sym_head_chunk_token1,
      sym_s_rr,
      sym_s_2r,
      sym_s_def,
      sym_s_lr,
  [988] = 5,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(101), 1,
      anon_sym_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(59), 8,
      ts_builtin_sym_end,
      sym__s_n,
      anon_sym_SLASH_STAR_BANG,
      aux_sym_head_chunk_token1,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
  [1011] = 5,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(103), 8,
      ts_builtin_sym_end,
      sym__s_n,
      anon_sym_SLASH_STAR_BANG,
      aux_sym_head_chunk_token1,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
  [1034] = 8,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(109), 1,
      anon_sym_COLON,
    ACTIONS(111), 1,
      aux_sym_plain_scalar_token2,
    ACTIONS(113), 1,
      aux_sym_plain_scalar_token3,
    STATE(23), 1,
      sym_comment,
    STATE(24), 1,
      aux_sym_plain_scalar_repeat1,
    ACTIONS(107), 4,
      sym__s_n,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1062] = 8,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(111), 1,
      aux_sym_plain_scalar_token2,
    ACTIONS(113), 1,
      aux_sym_plain_scalar_token3,
    ACTIONS(117), 1,
      anon_sym_COLON,
    STATE(24), 1,
      sym_comment,
    STATE(25), 1,
      aux_sym_plain_scalar_repeat1,
    ACTIONS(115), 4,
      sym__s_n,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1090] = 7,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(121), 1,
      anon_sym_COLON,
    ACTIONS(123), 1,
      aux_sym_plain_scalar_token2,
    ACTIONS(126), 1,
      aux_sym_plain_scalar_token3,
    STATE(25), 2,
      sym_comment,
      aux_sym_plain_scalar_repeat1,
    ACTIONS(119), 4,
      sym__s_n,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1116] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(129), 1,
      sym__s_n,
    ACTIONS(131), 1,
      sym_list_t,
    ACTIONS(133), 1,
      sym_s_list_sep,
    STATE(26), 1,
      sym_comment,
    STATE(30), 1,
      aux_sym_list_items_repeat1,
    STATE(69), 1,
      sym_list_items,
    ACTIONS(135), 2,
      anon_sym_PIPE,
      anon_sym_CR,
  [1145] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(27), 1,
      sym_comment,
    ACTIONS(137), 7,
      sym__s_n,
      anon_sym_STAR_SLASH,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1164] = 5,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(28), 1,
      sym_comment,
    ACTIONS(141), 2,
      anon_sym_COLON,
      aux_sym_plain_scalar_token2,
    ACTIONS(139), 5,
      sym__s_n,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      aux_sym_plain_scalar_token3,
  [1185] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(29), 1,
      sym_comment,
    ACTIONS(143), 7,
      sym__s_n,
      anon_sym_STAR_SLASH,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1204] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(131), 1,
      sym_list_t,
    ACTIONS(133), 1,
      sym_s_list_sep,
    ACTIONS(145), 1,
      sym__s_n,
    STATE(30), 1,
      sym_comment,
    STATE(31), 1,
      aux_sym_list_items_repeat1,
    ACTIONS(135), 2,
      anon_sym_PIPE,
      anon_sym_CR,
  [1230] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(147), 1,
      sym__s_n,
    ACTIONS(149), 1,
      sym_list_t,
    ACTIONS(152), 1,
      sym_s_list_sep,
    ACTIONS(155), 2,
      anon_sym_PIPE,
      anon_sym_CR,
    STATE(31), 2,
      sym_comment,
      aux_sym_list_items_repeat1,
  [1254] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(32), 1,
      sym_comment,
    ACTIONS(158), 6,
      sym__s_n,
      anon_sym_STAR_SLASH,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1272] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(33), 1,
      sym_comment,
    ACTIONS(160), 6,
      sym__s_n,
      anon_sym_STAR_SLASH,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1290] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    STATE(34), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_PIPE,
      anon_sym_CR,
    ACTIONS(162), 3,
      sym__s_n,
      sym_list_t,
      sym_s_list_sep,
  [1309] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(166), 1,
      anon_sym_STAR_SLASH,
    STATE(35), 1,
      sym_comment,
    STATE(58), 1,
      sym_flow_sequence,
    STATE(72), 1,
      sym_flow_mapping,
  [1334] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(36), 1,
      sym_comment,
    ACTIONS(168), 5,
      sym__s_n,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1351] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(37), 1,
      sym_comment,
    ACTIONS(170), 5,
      sym__s_n,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1368] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(38), 1,
      sym_comment,
    ACTIONS(172), 5,
      sym__s_n,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1385] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(174), 1,
      sym__s_n,
    ACTIONS(176), 1,
      sym_s_rr,
    ACTIONS(178), 1,
      sym_s_2r,
    ACTIONS(180), 1,
      sym_s_def,
    ACTIONS(182), 1,
      sym_s_lr,
    STATE(39), 1,
      sym_comment,
  [1410] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    STATE(40), 1,
      sym_comment,
    ACTIONS(186), 2,
      anon_sym_PIPE,
      anon_sym_CR,
    ACTIONS(184), 3,
      sym__s_n,
      sym_list_t,
      sym_s_list_sep,
  [1429] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(41), 1,
      sym_comment,
    ACTIONS(188), 5,
      sym__s_n,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1446] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(42), 1,
      sym_comment,
    ACTIONS(190), 5,
      sym__s_n,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1463] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(43), 1,
      sym_comment,
    ACTIONS(192), 5,
      sym__s_n,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1480] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(196), 1,
      anon_sym_COLON,
    STATE(44), 1,
      sym_comment,
    ACTIONS(194), 3,
      sym__s_n,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1498] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(198), 1,
      sym__s_n,
    ACTIONS(200), 1,
      anon_sym_SLASH,
    ACTIONS(202), 1,
      aux_sym_text_line_token1,
    STATE(45), 1,
      sym_comment,
    STATE(50), 1,
      aux_sym_text_line_repeat1,
  [1520] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(204), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(206), 1,
      aux_sym__comment_token1,
    ACTIONS(208), 1,
      anon_sym_STAR,
    STATE(46), 1,
      sym_comment,
    STATE(86), 1,
      sym__comment,
  [1542] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      sym_comment,
    STATE(52), 1,
      aux_sym_flow_mapping_entries_repeat1,
    ACTIONS(210), 2,
      sym__s_n,
      anon_sym_RBRACE,
  [1562] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(206), 1,
      aux_sym__comment_token1,
    ACTIONS(208), 1,
      anon_sym_STAR,
    ACTIONS(214), 1,
      anon_sym_STAR_SLASH,
    STATE(48), 1,
      sym_comment,
    STATE(88), 1,
      sym__comment,
  [1584] = 7,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(216), 1,
      anon_sym_DQUOTE,
    ACTIONS(218), 1,
      aux_sym__double_quoted_string_content_token1,
    ACTIONS(220), 1,
      sym_escape_sequence,
    STATE(49), 1,
      sym_comment,
    STATE(54), 1,
      aux_sym__double_quoted_string_content,
  [1606] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(222), 1,
      sym__s_n,
    ACTIONS(224), 1,
      anon_sym_SLASH,
    ACTIONS(227), 1,
      aux_sym_text_line_token1,
    STATE(50), 2,
      sym_comment,
      aux_sym_text_line_repeat1,
  [1626] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(200), 1,
      anon_sym_SLASH,
    ACTIONS(202), 1,
      aux_sym_text_line_token1,
    ACTIONS(230), 1,
      sym__s_n,
    STATE(45), 1,
      aux_sym_text_line_repeat1,
    STATE(51), 1,
      sym_comment,
  [1648] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      sym_comment,
    STATE(55), 1,
      aux_sym_flow_mapping_entries_repeat1,
    ACTIONS(49), 2,
      sym__s_n,
      anon_sym_RBRACE,
  [1668] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(206), 1,
      aux_sym__comment_token1,
    ACTIONS(208), 1,
      anon_sym_STAR,
    ACTIONS(234), 1,
      anon_sym_STAR_SLASH,
    STATE(53), 1,
      sym_comment,
    STATE(87), 1,
      sym__comment,
  [1690] = 6,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(236), 1,
      anon_sym_DQUOTE,
    ACTIONS(238), 1,
      aux_sym__double_quoted_string_content_token1,
    ACTIONS(241), 1,
      sym_escape_sequence,
    STATE(54), 2,
      sym_comment,
      aux_sym__double_quoted_string_content,
  [1710] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(244), 2,
      sym__s_n,
      anon_sym_RBRACE,
    STATE(55), 2,
      sym_comment,
      aux_sym_flow_mapping_entries_repeat1,
  [1728] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(249), 1,
      anon_sym_SLASH,
    STATE(56), 1,
      sym_comment,
    ACTIONS(222), 2,
      sym__s_n,
      aux_sym_text_line_token1,
  [1745] = 5,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(253), 1,
      aux_sym__double_quoted_string_content_token1,
    STATE(57), 1,
      sym_comment,
    ACTIONS(251), 2,
      anon_sym_DQUOTE,
      sym_escape_sequence,
  [1762] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(255), 1,
      anon_sym_STAR_SLASH,
    STATE(58), 1,
      sym_comment,
    STATE(70), 1,
      sym_flow_mapping,
  [1781] = 6,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym__double_quoted_string_content_token1,
    ACTIONS(220), 1,
      sym_escape_sequence,
    STATE(49), 1,
      aux_sym__double_quoted_string_content,
    STATE(59), 1,
      sym_comment,
  [1800] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(257), 1,
      anon_sym_COMMA,
    ACTIONS(259), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      sym_comment,
    STATE(65), 1,
      aux_sym_flow_sequence_entries_repeat1,
  [1819] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(61), 1,
      sym_comment,
    ACTIONS(244), 3,
      sym__s_n,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1834] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(62), 1,
      sym_comment,
    ACTIONS(261), 3,
      sym__s_n,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1849] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(265), 1,
      anon_sym_SLASH,
    STATE(63), 1,
      sym_comment,
    ACTIONS(263), 2,
      sym__s_n,
      aux_sym_text_line_token1,
  [1866] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      aux_sym_flow_sequence_entries_repeat1,
    STATE(64), 1,
      sym_comment,
  [1885] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(271), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RBRACK,
    STATE(65), 2,
      sym_comment,
      aux_sym_flow_sequence_entries_repeat1,
  [1902] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(66), 1,
      sym_comment,
    ACTIONS(276), 2,
      anon_sym_null,
      anon_sym_SQUOTE_SQUOTE,
  [1916] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(234), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(278), 1,
      anon_sym_STAR,
    STATE(67), 1,
      sym_comment,
  [1932] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    STATE(68), 1,
      sym_comment,
    ACTIONS(280), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1946] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(282), 1,
      sym__s_n,
    STATE(69), 1,
      sym_comment,
  [1959] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(284), 1,
      anon_sym_STAR_SLASH,
    STATE(70), 1,
      sym_comment,
  [1972] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(216), 1,
      anon_sym_SQUOTE,
    STATE(71), 1,
      sym_comment,
  [1985] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(255), 1,
      anon_sym_STAR_SLASH,
    STATE(72), 1,
      sym_comment,
  [1998] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(286), 1,
      sym__s_n,
    STATE(73), 1,
      sym_comment,
  [2011] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(288), 1,
      ts_builtin_sym_end,
    STATE(74), 1,
      sym_comment,
  [2024] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(290), 1,
      sym_identifier,
    STATE(75), 1,
      sym_comment,
  [2037] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      sym_comment,
  [2050] = 4,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(17), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(294), 1,
      sym__single_quoted_string_content,
    STATE(77), 1,
      sym_comment,
  [2063] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(296), 1,
      sym__s_n,
    STATE(78), 1,
      sym_comment,
  [2076] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(298), 1,
      sym__s_n,
    STATE(79), 1,
      sym_comment,
  [2089] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(300), 1,
      aux_sym_text_line_token2,
    STATE(80), 1,
      sym_comment,
  [2102] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(302), 1,
      sym__s_n,
    STATE(81), 1,
      sym_comment,
  [2115] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(304), 1,
      anon_sym_RBRACK,
    STATE(82), 1,
      sym_comment,
  [2128] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(306), 1,
      sym__s_n,
    STATE(83), 1,
      sym_comment,
  [2141] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      aux_sym_null_scalar_token1,
    ACTIONS(308), 1,
      sym__s_n,
    STATE(84), 1,
      sym_comment,
  [2154] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(310), 1,
      aux_sym_null_scalar_token1,
    STATE(85), 1,
      sym_comment,
  [2164] = 1,
    ACTIONS(312), 1,
      ts_builtin_sym_end,
  [2168] = 1,
    ACTIONS(314), 1,
      ts_builtin_sym_end,
  [2172] = 1,
    ACTIONS(316), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 68,
  [SMALL_STATE(4)] = 138,
  [SMALL_STATE(5)] = 208,
  [SMALL_STATE(6)] = 274,
  [SMALL_STATE(7)] = 342,
  [SMALL_STATE(8)] = 409,
  [SMALL_STATE(9)] = 473,
  [SMALL_STATE(10)] = 537,
  [SMALL_STATE(11)] = 601,
  [SMALL_STATE(12)] = 665,
  [SMALL_STATE(13)] = 726,
  [SMALL_STATE(14)] = 772,
  [SMALL_STATE(15)] = 820,
  [SMALL_STATE(16)] = 848,
  [SMALL_STATE(17)] = 876,
  [SMALL_STATE(18)] = 906,
  [SMALL_STATE(19)] = 938,
  [SMALL_STATE(20)] = 963,
  [SMALL_STATE(21)] = 988,
  [SMALL_STATE(22)] = 1011,
  [SMALL_STATE(23)] = 1034,
  [SMALL_STATE(24)] = 1062,
  [SMALL_STATE(25)] = 1090,
  [SMALL_STATE(26)] = 1116,
  [SMALL_STATE(27)] = 1145,
  [SMALL_STATE(28)] = 1164,
  [SMALL_STATE(29)] = 1185,
  [SMALL_STATE(30)] = 1204,
  [SMALL_STATE(31)] = 1230,
  [SMALL_STATE(32)] = 1254,
  [SMALL_STATE(33)] = 1272,
  [SMALL_STATE(34)] = 1290,
  [SMALL_STATE(35)] = 1309,
  [SMALL_STATE(36)] = 1334,
  [SMALL_STATE(37)] = 1351,
  [SMALL_STATE(38)] = 1368,
  [SMALL_STATE(39)] = 1385,
  [SMALL_STATE(40)] = 1410,
  [SMALL_STATE(41)] = 1429,
  [SMALL_STATE(42)] = 1446,
  [SMALL_STATE(43)] = 1463,
  [SMALL_STATE(44)] = 1480,
  [SMALL_STATE(45)] = 1498,
  [SMALL_STATE(46)] = 1520,
  [SMALL_STATE(47)] = 1542,
  [SMALL_STATE(48)] = 1562,
  [SMALL_STATE(49)] = 1584,
  [SMALL_STATE(50)] = 1606,
  [SMALL_STATE(51)] = 1626,
  [SMALL_STATE(52)] = 1648,
  [SMALL_STATE(53)] = 1668,
  [SMALL_STATE(54)] = 1690,
  [SMALL_STATE(55)] = 1710,
  [SMALL_STATE(56)] = 1728,
  [SMALL_STATE(57)] = 1745,
  [SMALL_STATE(58)] = 1762,
  [SMALL_STATE(59)] = 1781,
  [SMALL_STATE(60)] = 1800,
  [SMALL_STATE(61)] = 1819,
  [SMALL_STATE(62)] = 1834,
  [SMALL_STATE(63)] = 1849,
  [SMALL_STATE(64)] = 1866,
  [SMALL_STATE(65)] = 1885,
  [SMALL_STATE(66)] = 1902,
  [SMALL_STATE(67)] = 1916,
  [SMALL_STATE(68)] = 1932,
  [SMALL_STATE(69)] = 1946,
  [SMALL_STATE(70)] = 1959,
  [SMALL_STATE(71)] = 1972,
  [SMALL_STATE(72)] = 1985,
  [SMALL_STATE(73)] = 1998,
  [SMALL_STATE(74)] = 2011,
  [SMALL_STATE(75)] = 2024,
  [SMALL_STATE(76)] = 2037,
  [SMALL_STATE(77)] = 2050,
  [SMALL_STATE(78)] = 2063,
  [SMALL_STATE(79)] = 2076,
  [SMALL_STATE(80)] = 2089,
  [SMALL_STATE(81)] = 2102,
  [SMALL_STATE(82)] = 2115,
  [SMALL_STATE(83)] = 2128,
  [SMALL_STATE(84)] = 2141,
  [SMALL_STATE(85)] = 2154,
  [SMALL_STATE(86)] = 2164,
  [SMALL_STATE(87)] = 2168,
  [SMALL_STATE(88)] = 2172,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping_entries, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kvs_line, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping_entry, 2, 0, 5),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping_entries, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_sequence_entries, 2, 0, 6),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_line, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_sequence_entries, 3, 0, 8),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_head_chunk_repeat1, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_head_chunk_repeat1, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_head_chunk_repeat1, 2, 0, 0),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_head_chunk_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_head_chunk_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_head_chunk_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_head_chunk, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_head_chunk_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_scalar, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plain_scalar, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_scalar, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plain_scalar, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_plain_scalar_repeat1, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_plain_scalar_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_plain_scalar_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_plain_scalar_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_line, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_sequence, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_plain_scalar_repeat1, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_plain_scalar_repeat1, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_sequence, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_items, 1, 0, 4),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_items_repeat1, 2, 0, 7),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_items_repeat1, 2, 0, 7), SHIFT_REPEAT(34),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_items_repeat1, 2, 0, 7), SHIFT_REPEAT(40),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_items_repeat1, 2, 0, 7), SHIFT_REPEAT(34),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_items_repeat1, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_items_repeat1, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_scalar, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_null_scalar, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_scalar, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_other_line, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_items_repeat1, 1, 0, 3),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_items_repeat1, 1, 0, 3),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_null_scalar, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_node, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping_entry, 1, 0, 5),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_line, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping_entries, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_line_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_line_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_line_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_line, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__double_quoted_string_content, 2, 0, 0),
  [238] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__double_quoted_string_content, 2, 0, 0), SHIFT_REPEAT(57),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__double_quoted_string_content, 2, 0, 0), SHIFT_REPEAT(57),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_flow_mapping_entries_repeat1, 2, 0, 0),
  [246] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_flow_mapping_entries_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_text_line_repeat1, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__double_quoted_string_content, 1, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__double_quoted_string_content, 1, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_sequence_entries, 2, 0, 8),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping_entry, 3, 0, 9),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_line_repeat1, 1, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_text_line_repeat1, 1, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_sequence_entries, 1, 0, 6),
  [271] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_flow_sequence_entries_repeat1, 2, 0, 11), SHIFT_REPEAT(12),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_flow_sequence_entries_repeat1, 2, 0, 11),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [278] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_flow_sequence_entries_repeat1, 2, 0, 10),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_line, 3, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_line, 3, 0, 1),
  [288] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [294] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kvs_line, 3, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_line, 5, 0, 1),
  [300] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_line, 3, 0, 2),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_line, 4, 0, 1),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment, 3, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment, 2, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dct_txt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dct_txt",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
